# Generated by Django 4.2.4 on 2023-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whynotme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
