# Generated by Django 4.2.4 on 2023-08-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whynotme', '0002_alter_user_school_delete_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_nbr', models.CharField(max_length=20)),
                ('social_media', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=50)),
                ('player', models.BooleanField()),
            ],
        ),
    ]
